PROMPTS = [
    {"id": "stem_01_weighted_average_speed", "category": "stem_cs", "prompt": "Solve this exactly and show the final numeric answer only at the end: A train travels 180 miles in 3 hours and then 150 miles in 2 hours. What is the average speed for the entire trip in miles per hour?"},
    {"id": "stem_02_discount_tax", "category": "stem_cs", "prompt": "A store gives a 20% discount on a $75 item, then adds 8% sales tax on the discounted price. What is the final price? Show the calculation clearly."},
    {"id": "stem_03_quadratic_roots", "category": "stem_cs", "prompt": "Solve x^2 - 5x + 6 = 0 and explain the factoring in 2-3 sentences."},
    {"id": "stem_04_linear_algebra", "category": "stem_cs", "prompt": "Given vectors a=(2, -1, 4) and b=(1, 3, 0), compute a·b and the magnitude of a. Show the formulas used."},
    {"id": "stem_05_derivative_chain_rule", "category": "stem_cs", "prompt": "Differentiate f(x)=sin(x^2) and briefly explain why the chain rule applies."},
    {"id": "stem_06_integral_polynomial", "category": "stem_cs", "prompt": "Compute the indefinite integral of 3x^2 - 4x + 7 and include the constant of integration."},
    {"id": "stem_07_probability_draws", "category": "stem_cs", "prompt": "A bag contains 5 red, 3 blue, and 2 green marbles. If one marble is drawn at random, what is the probability it is blue or green? Simplify the fraction."},
    {"id": "stem_08_bayes_test", "category": "stem_cs", "prompt": "A disease affects 1% of people. A test has 95% sensitivity and 90% specificity. If a person tests positive, estimate the probability they actually have the disease using Bayes' rule."},
    {"id": "stem_09_combinatorics_committee", "category": "stem_cs", "prompt": "How many ways can a committee of 3 be chosen from 8 people? Give the formula and final answer."},
    {"id": "stem_10_modular_arithmetic", "category": "stem_cs", "prompt": "Compute 7^100 mod 13 and show the key simplification steps."},
    {"id": "stem_11_matrix_multiply", "category": "stem_cs", "prompt": "Multiply the matrices [[1,2],[3,4]] and [[2,0],[1,5]] and return the result in the same bracketed format."},
    {"id": "stem_12_statistics_mean_median", "category": "stem_cs", "prompt": "For the dataset [4, 7, 7, 9, 10, 13], compute the mean and median."},
    {"id": "stem_13_geometry_circle", "category": "stem_cs", "prompt": "A circle has radius 6. Compute its area and circumference in terms of pi and as decimals rounded to 2 places."},
    {"id": "stem_14_physics_velocity", "category": "stem_cs", "prompt": "An object starts from rest and accelerates at 3 m/s^2 for 8 seconds. What final velocity does it reach, and how far does it travel?"},
    {"id": "stem_15_physics_energy", "category": "stem_cs", "prompt": "A 2 kg object moves at 5 m/s. Compute its kinetic energy and state the formula used."},
    {"id": "stem_16_chemistry_moles", "category": "stem_cs", "prompt": "How many moles are in 18 grams of water (H2O)? Use the molar mass 18 g/mol and show the equation."},
    {"id": "stem_17_chemistry_balancing", "category": "stem_cs", "prompt": "Balance the chemical equation: Fe + O2 -> Fe2O3. Return only the balanced equation."},
    {"id": "stem_18_biology_mitosis", "category": "stem_cs", "prompt": "Explain the main purpose of mitosis in 3 concise bullet points."},
    {"id": "stem_19_astronomy_escape_velocity", "category": "stem_cs", "prompt": "In one short paragraph, explain what escape velocity means and why more massive bodies usually have higher escape velocities."},
    {"id": "stem_20_logic_truth_table", "category": "stem_cs", "prompt": "Create a truth table for the boolean expression A AND (NOT B) with columns A, B, NOT B, and Result."},
    {"id": "stem_21_python_fib_iter", "category": "stem_cs", "prompt": "Write a Python function named fib_iter that returns the nth Fibonacci number using iteration, not recursion. Include a short docstring and 3 example calls."},
    {"id": "stem_22_python_palindrome", "category": "stem_cs", "prompt": "Write a Python function is_palindrome(s: str) -> bool that ignores spaces and letter case. Include 4 assert-style examples."},
    {"id": "stem_23_python_frequency_map", "category": "stem_cs", "prompt": "Write a Python function that takes a list of strings and returns a dictionary mapping each string to its count. Keep the implementation concise."},
    {"id": "stem_24_python_merge_intervals", "category": "stem_cs", "prompt": "Write Python code to merge overlapping intervals in a list like [[1,3],[2,6],[8,10],[9,12]]. Include the expected output for that example."},
    {"id": "stem_25_python_bfs", "category": "stem_cs", "prompt": "Write a Python function that performs breadth-first search on an adjacency-list graph and returns the visitation order starting from a given node."},
    {"id": "stem_26_sql_groupby", "category": "stem_cs", "prompt": "Given a table orders(customer_id, amount), write SQL to return each customer_id with total spend, sorted from highest to lowest total spend."},
    {"id": "stem_27_sql_topn_per_group", "category": "stem_cs", "prompt": "Write SQL to return the highest-paid employee in each department from a table employees(department, employee_name, salary)."},
    {"id": "stem_28_cpp_vector_sum", "category": "stem_cs", "prompt": "Write a short C++ function that returns the sum of all integers in a std::vector<int>."},
    {"id": "stem_29_rust_option", "category": "stem_cs", "prompt": "Explain Rust's Option<T> in plain English and show a tiny code example using match."},
    {"id": "stem_30_javascript_async", "category": "stem_cs", "prompt": "Explain the difference between async/await and Promise.then() in JavaScript with one short code example for each."},
    {"id": "stem_31_algorithm_big_o", "category": "stem_cs", "prompt": "Explain the time complexity of binary search and why it is better than linear search on sorted data."},
    {"id": "stem_32_algorithm_dynamic_programming", "category": "stem_cs", "prompt": "In 4-6 sentences, explain what dynamic programming is and when it is useful."},
    {"id": "stem_33_data_structures_heap", "category": "stem_cs", "prompt": "What is a binary heap, and what are two common operations with their typical time complexities?"},
    {"id": "stem_34_networking_tcp_udp", "category": "stem_cs", "prompt": "Compare TCP and UDP in a compact table with columns Protocol, Reliable, Ordered, and Common Use Cases."},
    {"id": "stem_35_operating_systems_threads", "category": "stem_cs", "prompt": "Explain the difference between a process and a thread in 5 concise bullet points."},
    {"id": "stem_36_distributed_systems_consistency", "category": "stem_cs", "prompt": "What is eventual consistency in distributed systems? Give a practical example in 3-5 sentences."},
    {"id": "stem_37_machine_learning_overfitting", "category": "stem_cs", "prompt": "Define overfitting in machine learning and list 4 common mitigation strategies."},
    {"id": "stem_38_machine_learning_precision_recall", "category": "stem_cs", "prompt": "Explain precision and recall and describe when recall matters more than precision."},
    {"id": "stem_39_llm_temperature", "category": "stem_cs", "prompt": "What does temperature control in text generation, and how does temperature=0 typically affect outputs?"},
    {"id": "stem_40_gpu_kernel_basics", "category": "stem_cs", "prompt": "In one paragraph, explain what a GPU kernel is and why memory access patterns matter for performance."},
    {"id": "stem_41_rocm_atom_summary", "category": "stem_cs", "prompt": "Summarize the following in exactly 3 bullet points:\n\nATOM is a lightweight LLM inference engine built on AITER GPU kernels for the AMD ROCm platform. Its main execution path is OpenAI server to LLMEngine to CoreManager to EngineCore to Scheduler to ModelRunner. The repository supports multiple sparse MoE models and emphasizes efficient inference, multiprocessing with spawn, and OpenAI-compatible serving."},
    {"id": "stem_42_json_extraction_roles", "category": "stem_cs", "prompt": "Extract the people and their roles from this text and return only valid JSON with a top-level key named people: 'Alice is the CTO, Bob leads infrastructure, and Carol is a senior ML engineer.'"},
    {"id": "stem_43_markdown_planets", "category": "stem_cs", "prompt": "Create a markdown table with columns Planet, Type, and Moons for Earth, Mars, and Jupiter. Keep it concise."},
    {"id": "stem_44_classification_items", "category": "stem_cs", "prompt": "Classify each item as fruit, vegetable, or mineral and return one item per line in the format item: category\n\napple\ncarrot\nquartz\nbanana\nspinach"},
    {"id": "stem_45_defensive_api_security", "category": "stem_cs", "prompt": "Give 5 concise defensive cybersecurity best practices for securing an internal API service. Do not include offensive or exploit instructions."},
    {"id": "stem_46_regex_log_parse", "category": "stem_cs", "prompt": "Write a Python regular expression that extracts the status code from lines like 'GET /health 200 12ms' and explain the capture group."},
    {"id": "stem_47_unit_conversion", "category": "stem_cs", "prompt": "Convert 72 kilometers per hour to meters per second and show the conversion."},
    {"id": "stem_48_fraction_simplify", "category": "stem_cs", "prompt": "Add 5/12 and 7/18, simplify the result, and show the least common denominator used."},
    {"id": "stem_49_sequence_pattern", "category": "stem_cs", "prompt": "Find the next two numbers in the sequence 2, 6, 12, 20, 30 and explain the pattern briefly."},
    {"id": "stem_50_graph_shortest_path", "category": "stem_cs", "prompt": "Given edges A-B(2), A-C(5), B-C(1), B-D(4), C-D(1), what is the shortest path from A to D and its total weight?"},
    {"id": "stem_51_set_operations", "category": "stem_cs", "prompt": "Let A={1,2,3,4} and B={3,4,5}. Compute A union B, A intersection B, and A minus B."},
    {"id": "stem_52_binary_hex", "category": "stem_cs", "prompt": "Convert the binary number 11010110 to decimal and hexadecimal."},
    {"id": "stem_53_recurrence_relation", "category": "stem_cs", "prompt": "Given a_n = 2a_(n-1) + 1 with a_1 = 1, compute a_2 through a_5."},
    {"id": "stem_54_trigonometry_identity", "category": "stem_cs", "prompt": "State the Pythagorean trigonometric identity and give one example of how it can simplify an expression."},
    {"id": "stem_55_database_index", "category": "stem_cs", "prompt": "What is a database index, and what is one tradeoff of adding many indexes?"},
    {"id": "stem_56_http_status_codes", "category": "stem_cs", "prompt": "Explain the difference between HTTP 200, 404, and 500 in one sentence each."},
    {"id": "stem_57_git_rebase_merge", "category": "stem_cs", "prompt": "Compare git merge and git rebase in 4 concise bullet points."},
    {"id": "stem_58_cache_eviction", "category": "stem_cs", "prompt": "What is LRU cache eviction, and why is it useful? Give one example scenario."},
    {"id": "stem_59_schema_design", "category": "stem_cs", "prompt": "Design a minimal JSON schema for a user profile with required fields id, name, and email, and an optional field company."},
    {"id": "stem_60_test_case_design", "category": "stem_cs", "prompt": "List 6 useful test cases for a function that parses positive integers from strings."},
    {"id": "writing_01_plain_english_rewrite", "category": "writing", "prompt": "Rewrite this sentence in plain English for a non-technical audience: 'The system leverages distributed inference orchestration to optimize heterogeneous accelerator utilization.'"},
    {"id": "writing_02_haiku_gpu_winter", "category": "writing", "prompt": "Write a haiku about GPU kernels and winter. Exactly 3 lines."},
    {"id": "writing_03_formal_email", "category": "writing", "prompt": "Draft a polite 5-sentence email asking a teammate to review a pull request before end of day."},
    {"id": "writing_04_product_blurb", "category": "writing", "prompt": "Write a 60-word product blurb for a fast local LLM inference engine aimed at enterprise developers."},
    {"id": "writing_05_headline_options", "category": "writing", "prompt": "Generate 8 headline options for a blog post about improving inference throughput on AMD GPUs."},
    {"id": "writing_06_meeting_summary", "category": "writing", "prompt": "Turn these notes into a concise meeting summary with action items:\n- accuracy issue still open\n- TP=8 benchmark completed\n- TP=4 blocked on expert parallel bug\n- next step is larger correctness sweep"},
    {"id": "writing_07_story_opening", "category": "writing", "prompt": "Write an opening paragraph for a science fiction story set inside a data center during a winter storm."},
    {"id": "writing_08_compare_tones", "category": "writing", "prompt": "Write two versions of the same message announcing a delayed release: one formal and one friendly."},
    {"id": "writing_09_bullets_to_paragraph", "category": "writing", "prompt": "Convert these bullets into a short paragraph: reliable serving, lower latency, simpler deployment, better observability."},
    {"id": "writing_10_edit_for_clarity", "category": "writing", "prompt": "Edit this for clarity and concision: 'At this point in time, we are currently in the process of evaluating a variety of different alternatives for the deployment path.'"},
    {"id": "writing_11_tagline_variants", "category": "writing", "prompt": "Generate 10 short tagline options for a benchmark dashboard."},
    {"id": "writing_12_argumentative_paragraph", "category": "writing", "prompt": "Write one persuasive paragraph arguing that correctness checks should come before performance claims."},
    {"id": "writing_13_linkedin_post", "category": "writing", "prompt": "Draft a professional LinkedIn-style post announcing a new long-context benchmark milestone for an inference engine."},
    {"id": "writing_14_changelog_entry", "category": "writing", "prompt": "Write a release note entry for a benchmark script update that now skips unsupported TP configurations and survives transient request failures."},
    {"id": "writing_15_microcopy_warning", "category": "writing", "prompt": "Write three concise warning messages for a UI that shows provisional benchmark results before correctness validation is complete."},
    {"id": "writing_16_poem_datacenter", "category": "writing", "prompt": "Write a 4-line free verse poem about fans, racks, and midnight debugging."},
    {"id": "writing_17_style_transfer", "category": "writing", "prompt": "Rewrite this in a more confident tone: 'We think this might help improve throughput a bit.'"},
    {"id": "writing_18_commit_message_help", "category": "writing", "prompt": "Suggest 5 concise git commit messages for a change that expands a prompt set from 10 to 100 and categorizes the prompts."},
    {"id": "writing_19_doc_intro", "category": "writing", "prompt": "Write a brief introduction section for documentation titled 'Correctness Comparison Workflow'."},
    {"id": "writing_20_slogan", "category": "writing", "prompt": "Create 6 short slogan options about balancing speed and correctness in AI systems."},
    {"id": "misc_01_trip_planning", "category": "misc", "prompt": "Plan a one-day visit to Seattle for someone who likes coffee, books, and quiet neighborhoods. Use a morning/afternoon/evening format."},
    {"id": "misc_02_recipe_scaling", "category": "misc", "prompt": "A recipe serves 4 and uses 2 cups of rice, 1 pound of chicken, and 3 tablespoons of soy sauce. Scale it to serve 10."},
    {"id": "misc_03_movie_recommendations", "category": "misc", "prompt": "Recommend 5 thoughtful science fiction films and give one-sentence reasons for each."},
    {"id": "misc_04_book_genres", "category": "misc", "prompt": "Classify these books by likely genre: Dune, The Hobbit, The Name of the Rose, Neuromancer, Pride and Prejudice."},
    {"id": "misc_05_travel_packing", "category": "misc", "prompt": "Make a packing checklist for a 3-day winter business trip."},
    {"id": "misc_06_habit_plan", "category": "misc", "prompt": "Create a simple 7-day plan for building a daily reading habit."},
    {"id": "misc_07_budget_breakdown", "category": "misc", "prompt": "Given a monthly take-home pay of $4,200, propose a simple budget with categories for housing, food, transport, savings, utilities, and fun."},
    {"id": "misc_08_table_restaurants", "category": "misc", "prompt": "Create a markdown table with columns Cuisine, Typical Spice Level, and Example Dish for Italian, Thai, and Ethiopian food."},
    {"id": "misc_09_compare_cameras", "category": "misc", "prompt": "Compare mirrorless and DSLR cameras in 5 concise bullet points."},
    {"id": "misc_10_pet_advice", "category": "misc", "prompt": "Give 5 practical tips for helping a newly adopted cat adjust to a home."},
    {"id": "misc_11_event_schedule", "category": "misc", "prompt": "Create a simple schedule for a 2-hour community meetup with check-in, talk, break, discussion, and wrap-up."},
    {"id": "misc_12_resume_bullets", "category": "misc", "prompt": "Write 4 resume bullet points for someone who improved internal tooling, automated reporting, and reduced deployment friction."},
    {"id": "misc_13_language_learning", "category": "misc", "prompt": "Suggest a 20-minute daily routine for someone beginning to learn Spanish."},
    {"id": "misc_14_home_organization", "category": "misc", "prompt": "Give a step-by-step plan to organize a cluttered desk in under 30 minutes."},
    {"id": "misc_15_decision_matrix", "category": "misc", "prompt": "Make a small decision matrix comparing bike, bus, and car commuting for cost, speed, and convenience."},
    {"id": "misc_16_gift_ideas", "category": "misc", "prompt": "Suggest 8 gift ideas for someone who likes cooking, gardening, and science fiction."},
    {"id": "misc_17_health_sleep", "category": "misc", "prompt": "List 6 evidence-aligned habits that generally support better sleep. Keep it practical and non-medical."},
    {"id": "misc_18_museum_caption", "category": "misc", "prompt": "Write a 2-sentence museum-style caption for an imaginary bronze astrolabe from the 17th century."},
    {"id": "misc_19_weekend_menu", "category": "misc", "prompt": "Create a simple weekend dinner menu for Friday, Saturday, and Sunday with one vegetarian option."},
    {"id": "misc_20_icebreaker_questions", "category": "misc", "prompt": "Generate 12 good icebreaker questions for a small team offsite."},
]
